spring.application.name=ai-job-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/aijob
spring.datasource.username=dineshmaharana
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
